### PR TITLE
Add a docker-compose.yml file, update Docker instructions in README

### PR DESCRIPTION
**Pull request by Kovah**
This adds a simple docker-compose file that contains the configuration of the one long `docker run` command. Docker Compose is quite easier to work with than plain Docker commands.
I updated the readme accordingly with additional information. Also added a hint about persisting archive data which would be very helpful for updating the Docker image later on.

### CODE REVIEW

**Comment by Kovah** [comment]
BTW: I have some experience with Docker so if I can help with that just throw your questions at me. 🤓

**Comment by Kovah** [comment]
Are you still interested in this?

**Comment by erangell** [comment]
IMHO, even if this PR is not merged, there is still interest in making homebase easier for novice users to set up and configure, and improving documentation.

**Comment by pfrazee** [comment]
I don't have a ton of time to maintain this atm but if there's interest in a fork, I'd be happy to link to it from this one's readme

**Pull request closed without merging**
