### PR TITLE
Add Docker && a default .homebase.yml

### PR DESCRIPTION
**Pull request by hossameldeen**
**Goal:** Setup Homebase through Docker.

**Summary of changes:**
- Added a `Dockerfile` and `.dockerignore` that assumes production settings, following [this article](https://nodejs.org/en/docs/guides/nodejs-docker-webapp/).
- Added a default `.homebase.yml` to be used in the `Dockerfile`.
- Added instructions in `README.md`.

**Notes:**
- I understand if you don't want to include Docker in order to not complicate things. I was setting things up for myself & documenting the steps anyway.
- Not a Docker expert and didn't necessarily setup things in the _best_ way possible.
- If one wants to include Prometheus and Grafana, they're on their own. I did make a setup with [Docker Compose](https://docs.docker.com/compose/) but got no data in the end. Didn't continue that path. If you want docker-compose setup, I think I may still have it.
- Needless to say, feel free to make any edits on anything.

**Disclaimer**: Perhaps my first serious PR; not sure of the etiquette.

**Update:** I'm currently having difficulties with homebase: connectivity problems and sudden shutdown. Not sure if the problem is with homebase or docker (probably it's docker). Prefer to keep this PR on hold till I resolve the problem.  
Should report back soon.

### CODE REVIEW

**Comment by hossameldeen** [comment]
Reporting back:

- Fixed some problems I had in build. Now, it runs without shutting down.
- However, dat serving is not stable at all. It's as if it's always working with at most one dat a time.

Is there any chance that multiple dats calling [`dat.joinNetwork()`](https://github.com/beakerbrowser/homebase/blob/master/lib/vhosts/dat.js#L25) without providing different `port`s in `opts` could cause a problem, or can multiple `dat.joinNetwork()` work on the same port?

If there's no problem with the line above, I give up on integrating Docker and this PR can be closed.

**Comment by hossameldeen** [comment]
Update: I left homebase's docker running yesterday with some dats configured but I couldn't clone them. When I came today and tried to clone, it clones successfully from homebase's docker, without changing anything O.o. It's as if it needed to warm-up or something.

I really don't know whether to consider this a problem of homebase & merge the PR anyway, or to consider it a problem of docker.

**Comment by pfrazee** [comment]
> Is there any chance that multiple dats calling dat.joinNetwork() without providing different ports in opts could cause a problem, or can multiple dat.joinNetwork() work on the same port?

I think there is a chance of that. I need to move hashbase onto https://github.com/beakerbrowser/dat-node

**Comment by pfrazee** [comment]
👍 This looks good, merging. Thanks for the PR.

**Pull request merged**
