### PR TITLE
Version 2, improve config clarity (WIP)

### PR DESCRIPTION
**Pull request by pfrazee**
People have found the yaml a bit confusing to work with (https://github.com/beakerbrowser/homebase/issues/7). This PR is meant to solve that by simplifying configuration.

 - [x] Removes `dats.*.name`
 - [x] Moves the top-level `domain` config to be inside the `webapi` config object. This will lend some clarity about *which* domain is being set. 
 - [x] Inside the `dats` list, renames the `otherDomains` field to just `domains`.
 - [x] Tolerates `dats.*.domain` (the singular)

Makes the following configs valid:

```yaml
dats:
  - url: dat://1f968afe867f06b0d344c11efc23591c7f8c5fb3b4ac938d6000f330f6ee2a03/
    domain: mysite.com
```

```yaml
dats:
  - url: dat://1f968afe867f06b0d344c11efc23591c7f8c5fb3b4ac938d6000f330f6ee2a03/
    domains:
      - mysite.com
      - my-site.com
```

```yaml
webapi:
  domain: foo.com
  user: bob
  password: asdf
dats:
  - url: dat://1f968afe867f06b0d344c11efc23591c7f8c5fb3b4ac938d6000f330f6ee2a03/
    domains:
      - mysite.com
      - my-site.com
```

### CODE REVIEW

**Comment by webdesserts** [comment]
Here's my thoughts on the above examples:

### Example 1

First example is really nice and clean. Would make tutorials a cinche to build on.

### Example 2

With the new `dats.*.domain` can I add a subdomain?

```yml
dats:
  - url: dat://1f968afe867f06b0d344c11efc23591c7f8c5fb3b4ac938d6000f330f6ee2a03/
    domain: blog.mysite.com
```

If so, it might be reasonable to expect the following to work too, though I'm assuming it doesn't:

```yml
dats:
  - url: dat://1f968afe867f06b0d344c11efc23591c7f8c5fb3b4ac938d6000f330f6ee2a03/
    name: blog
    domain: mysite.com
```

### Example 3

In the third example, if I didn't want to use the web api, but I still wanted to use the `name` field would I have to do the following?

```yml
webapi:
  domain: foo.com
dats:
  - url: dat://1f968afe867f06b0d344c11efc23591c7f8c5fb3b4ac938d6000f330f6ee2a03/
    name: mysite
```

Seems a bit weird. I guess I don't completely understand why the domain field was moved into the `webapi` object. It seems to apply to more than just the webapi (as long as `name` is around).

---

I like the idea of trying to provide both a top-level domain and a per-dat domain, but I think that the mix of piecemealed and absolute urls that have multiple purposes is currently a bit confusing. I'm going to think on it some more and see if I can come up with any suggestions.

**Comment by webdesserts** [comment]
@pfrazee I thought through all the use cases this morning. I _actually_ think the api would be much simpler with `name` removed (somewhat contrary to my comment on #7). If you want to add a sub domain, just add the full domain to `dats.*.domain`. I think it makes the config straight forward and easy to understand at a glance.

The downside would be that you would need to do a bit more copy/paste and if you wanted to change domains you would have to do a find/replace, but I imagine that happens infrequently enough that it might not matter.

Here's some examples of what that might look like:

### Single Domain Root

```yml
dats: 
  - url: a1b2c3...
    domain: webdesserts.com
```

### Single Sub Domain

```yml
dats: 
  - url: a1b2c3...
    domain: www.webdesserts.com
```

### Multiple Domains

```yml
dats: 
  - url: a1b2c3...
    domain: webdesserts.com
  - url: a1b2c3...
    domain: dessert.technology
```

### Domain-less Dats

```yml
dats: 
  - url: a1b2c3...
  - url: a1b2c3...
  - url: a1b2c3...
```

### WebAPI

```yml
webapi:
    domain: webdesserts.com
    user: me
    password: p^55w0rd
dats: 
  - url: a1b2c3...
    domain: webdesserts.com
  - url: a1b2c3...
    domain: term.webdesserts.com
  - url: a1b2c3...
    domain: dashboard.webdesserts.com
```

### Mixture

```yml
webapi:
    domain: webdesserts.com
    user: me
    password: p^55w0rd
dats: 
  - url: a1b2c3...
  - url: a1b2c3...
    domain: www.webdesserts.com
  - url: a1b2c3...
    domain: term.webdesserts.com
  - url: a1b2c3...
    domain: dessert-recipes.com
```

**Comment by pfrazee** [comment]
No names does make sense. I think I can make that work with the spec.

**Comment by pfrazee** [comment]
Another option is, we could disconnect `name` from `subdomain`, but have the Web API automatically add the subdomain when it's POSTed with a name.

So a POST `{"name": "foo"}` adds to the list of domains (thus: `{"name": "foo", "domains": ["foo.bar.com"]}`, but putting a `name: foo` in the config does not.

**Comment by webdesserts** [comment]
For some background, my original thought was that the `name` would still exist in the Web API, and would just not be exposed in the config. You could instead derive what the `name` was from diffing `webapi.domain` and `dats.*.domain`.

So in the following example, we would tell homebase that the `webapi` would be responsible for  adding and removing subdomains for `dessert.com`, and homebase would figure out that there is currently a dat with the name `strawberry`.

```yml
webapi:
    domain: dessert.com
    user: me
    password: p^55w0rd
dats: 
  - url: a1b2c3...
    domain: strawberry.dessert.com
```

In the same vein, you should be able to determine which "additional" domains are listed by just returning any domain that does not contain `webapi.domain`. The config is just another type of UI, we don't necessarily need to match the webapi scheme as long as we can map to it.

This was assumming that, for the purposes of homebase at least, `name == subdomain`. I'd be interested in what else you had imagined it being used for. Perhaps subroutes or a term in a searchable interface?

---

That said, although I'm not _tooo_ opinionated on what you do with the Web API itself, it does seem relying on the name/domain split might cause issues in the future if you have to manage multiple domains in the same pinning service.

I'd imagine that eventually a pinning service might look like the combination of a DNS provider and a hosting service. The client might first ask the service "what domains does this user own?" and then provide a UI to the user that allows them to publish under any of those given domains.

For that to work, I think you would have to provide both the `name` _and_ the `domain` in some form. So yeah, in summary I think you might end up needing to supply a full domain eventually anyway, so might as well do it now.

(side note: it would be _reaaally_ nice if one day you could both buy a domain & pubilsh to it from the browser. Would just completely strip all the complexity out of publishing to the web)

**Comment by pfrazee** [comment]
That's a pretty good point about the user needing to own domains (and yes I agree, it'd be amazing if domain purchasing could be integrated into these flows). Let's step back a bit.

Let's start by looking at Hashbase (using hashbase.io as its domain, but folks can self-host it elsewhere). The service has at least one "shared" domain at `hashbase.io`. So the user is able to attach to the following domains:

 - `*.hashbase.io`

Suppose the user gets their own domain at `foo.com` and proves to Hashbase that they own it. Then *that* user has the following domains available to them:

 - `*.hashbase.io`
 - `foo.com`
 - `*.foo.com`

And Hashbase could bind to any of those, so long as `foo.com` points at its URL. Then, technically, the Hashbase instance could add more shared domains, eg `hashbase.me`, and then that user would have these domains available to them:

 - `*.hashbase.io`
 - `*.hashbase.me`
 - `foo.com`
 - `*.foo.com`

The situation is actually similar with Homebase. The only difference is that there's no "shared" domain, and no need to prove ownership of a given domain. So Homebase can technically accept any domain via the Web API and just be like "okay cool."

From the perspective of Hashbase, every user has an inventory of domains and subdomains that they can bind to. From the perspective of Homebase, the user can bind to any domain, and there's no need to manage the inventory. (That said, we *could* give Homebase a "domains inventory" if we found that easier for users.)

WIth that understood, let's look at the `name` field. The `name` field was introduced by Hashbase, and then Homebase adopted it in order to provide the same Web API as Hashbase. It serves two functions on Hashbase:

 - To provide dashboard addresses, such as https://hashbase.io/pfrazee/pfrazee
 - To set the subdomains, such as `pfrazee.hashbase.io`

So, basically, Hashbase used a very simplified concept of the domains inventory, where `name` was used as the subdomain of one shared top domain.

So, where can we take this?

Well, I think it's fair to assume that Hashbase is going to need to expand its concept of how domains work, because it doesn't yet support user-owned domains or multiple shared domains. That means that Hashbase is probably going to need to rethink using `name` to set the subdomain.

Here's what I see happening to Hashbase:

 - Detach `name` from setting the subdomain. Instead, the Web API will use the `domains` portion of the request. The `name` will just be used for view pages.
 - Create an internal concept of the domains inventory. Reject any requests to bind to a domain that's not in the user's domains inventory.
 - (Maybe in the future) Create a new Web API spec for a user to get its domain inventory, so that a client can help the user pick their domains.

As a result, here's what I see happening to Homebase:

 - Just drop the `name` field and use domains. There's no use for it internally, and if there's no parity with Hashbase that we have to match, then there's no reason to have it.

@webdesserts long write-up, I know. Sorry about that! Thanks for slogging through this with me. WDYT?

**Comment by webdesserts** [comment]
@pfrazee Thanks for writing this up, it's good to see the thought process written out. I think we're pretty much on the same page and your recommended path forward sounds good to me 👍🏼. Looking forward to it!

**Comment by pfrazee** [comment]
@webdesserts thanks for helping me step through it!

Another suggestion we got in IRC was, make the domain optional on the web api. Seems like something we can easily do with the new changes.

**Comment by webdesserts** [comment]
@pfrazee Yeah, I could see that working

I'm guessing a domainless `webapi` config could accept any domain with no complaint (just might not work):

```yml
webapi:
    user: me
    password: p^55w0rd
```
```http
POST /add {
  url: "dat://a1b2c3..."
  domains: ["webdesserts.com"]
}
```
```http
200 OK
```
```yml
webapi:
    user: me
    password: p^55w0rd
dats:
  - url: dat://a1b2c3...
    domain: webdesserts.com
```

---

And with the domains included it would respond with an error if you tried to publish to an unlisted domain:

```yml
webapi:
  domains:
    - webdesserts.com
    - dsrt.co
  user: me
  password: p^55w0rd
```
```http
POST /add {
  url: "dat://a1b2c3..."
  domains: ["webdesserts.com", "dsrt.co", "dessert.technology"]
}
```
```http
403 Forbidden {
  error: "Unrecognized Domain"
  message: "At least one of the given domains was not recognized by this service"
  domains: ["dessert.technology"]
}
```

---

Am I guessing that right? Long term, if we have a way to list webapi domains, it would also be nice to have a way to update them. Then you might never need to manually touch the config again.

**Comment by pfrazee** [comment]
Okay this is ready to merge. Will publish `2.0.0` after some final testing.

**Pull request merged**
